In [5]:
import torch

In [6]:
torch.get_default_dtype()

torch.float32

In [9]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
torch.is_tensor(tensor_arr)

True

In [11]:
torch.numel(tensor_arr)

6

In [12]:
tensor_uninitialized = torch.Tensor(2,2)

In [13]:
tensor_uninitialized

tensor([[0., 0.],
        [0., 0.]])

In [14]:
tensor_initialized = torch.rand(2,2)
tensor_initialized

tensor([[0.9569, 0.9313],
        [0.4223, 0.0388]])

In [15]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [16]:
tensor_short = torch.ShortTensor([1.0, 2.0,3.0])
tensor_short


tensor([1, 2, 3], dtype=torch.int16)

In [17]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float


tensor([1., 2., 3.], dtype=torch.float16)

In [18]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [19]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [20]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [21]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [23]:
makes_a_copy_of_data = torch.tensor([[0,1,1],[2,2,0]])

In [24]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.1889, 0.9258, 0.0725],
        [0.1229, 0.0254, 0.6936]])

In [25]:
initial_tensor.fill_(10)  #in-place operation(modify the original tensor)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [26]:
new_tensor = initial_tensor.add(5) #out-of-place operation(does not modify the original tensor and creates a new tensor)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [27]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [28]:
another_tensor = initial_tensor.add_(5)
another_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [29]:
initial_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [30]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [31]:
x = torch.linspace(start=0.1, end=10.0, steps=15)  #1dimentional tensor with 15 elements that are evenly spaced numbers between 0.1 and 10
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [32]:
tensor_chunk = torch.chunk(x,3,0) #take the x tensor and break it into 3 tensors starting a 0
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [33]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0,4.0,5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [35]:
random_tensor = torch.Tensor([[10,8,30], [40,5,6], [12,2,21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [36]:
random_tensor[0,1] # accessing a value in a tensor 

tensor(8.)

In [37]:
random_tensor[1:,1:] 

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [38]:
random_tensor.size()

torch.Size([3, 3])

In [41]:
tensor_view = random_tensor.view(3,3) # the view shares the same memory as the original tensor so any changes will change both tensors

In [42]:
random_tensor[2,2] = 100.0 # the view shares the same memory as the original tensor so any changes will change both tensors
tensor_view

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [43]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [45]:
random_tensor.shape

torch.Size([3, 3])

In [46]:
#did not write the unsqueeze, squeeze, and transpose operations

In [47]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [48]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [49]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [54]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))

tensor([[0.6786, 0.9492, 2.0607],
        [0.5967, 1.1263, 0.4794]])

In [51]:
add = torch.add(rand1, rand2)
add

tensor([[2.2643, 3.2086, 2.4658],
        [0.4786, 1.3390, 1.0947]])

In [55]:
rand1

tensor([[0.0031, 0.1539, 0.7157],
        [0.1690, 1.1599, 1.0215]])

In [56]:
rand2

tensor([[0.6786, 0.9492, 2.0607],
        [0.5967, 1.1263, 0.4794]])

In [59]:
multiply = torch.mul(rand1, rand2)
multiply


tensor([[0.0021, 0.1461, 1.4747],
        [0.1009, 1.3064, 0.4897]])

In [62]:
tensor_clamp = torch.clamp(random_tensor, min=2, max=40)
tensor_clamp

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 40.]])

In [66]:
t1= torch.Tensor([1,2])
t2= torch.Tensor([10,20])
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

In [67]:
matrix = torch.Tensor([[1,2,3],[4,5,6]])
vector = torch.Tensor([0,1,2])

In [68]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

In [77]:
import numpy as np

In [70]:
tensor = torch.rand(4,3)
tensor

tensor([[0.4015, 0.5164, 0.0301],
        [0.6893, 0.6021, 0.7382],
        [0.4853, 0.5265, 0.1898],
        [0.2931, 0.7361, 0.3910]])

In [71]:
type(tensor)

torch.Tensor

In [72]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.40147352, 0.51638657, 0.03014112],
       [0.6892794 , 0.6021155 , 0.73818654],
       [0.48525792, 0.5265437 , 0.18975133],
       [0.2930898 , 0.73605394, 0.39099067]], dtype=float32)

In [73]:
type(numpy_from_tensor) # The Numpy array and the PyTorch tensor share the same underlying memory

numpy.ndarray

In [78]:
numpy_arr = np.array([[1.0,2.0,3.0], [10.0,20.0,30.0], [100.0,200.0,300.0]])

In [79]:
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [80]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [81]:
type(tensor_from_numpy)

torch.Tensor